.github/workflows/cmake.yml

Enable Hypre and PETSc testing

Full tests

---

docker/clion/Dockerfile
docker/clion/README.md

Dockerfile to compile and debug  in a container from Clion

Development with Clion and docker

---

docker/clion/Dockerfile

Adding rsync to container.
Improves #16

fix clion interaction

---

.github/workflows/cmake.yml
CMakeLists.txt
src/modules/core/src/alien/kernels/simple_csr/algebra/CMakeLists.txt
src/test/tests/ref_api/CMakeLists.txt
src/test/tests/ref_api/TestRedistributor.cc

Fix installation and add install phase

---

.github/workflows/cmake.yml
CHANGELOG.md
CMake/sanitizers.cmake
CMakeLists.txt
docker/base/ubuntu-20.04/Dockerfile
src/modules/core/src/CMakeLists.txt
src/modules/movesemantic/CMakeLists.txt
src/modules/refsemantic/CMakeLists.txt

- Add sanitizer options
- Add `ALIEN_DEFAULT_OPTIONS`: Fix #24

Better CI and configuration

---

.github/workflows/ifpen_el7_foss-2018b.yml
.github/workflows/ifpen_el7_gimkl-2018b.yml
.github/workflows/ifpen_el8_foss-2018b.yml
.github/workflows/ifpen_el8_gimkl-2018b.yml

- pull anonymously docker images,
- don't run ifpen foss workflows on PR,
- allow run manually ifpen workflows on all branches.

CI IFPEN : update

---

docker/base/ubuntu-20.04/Dockerfile
docker/clion/Dockerfile

A first joke PR :)
Welcome to open source alien !

Fix typo in Dockerfiles

---

CHANGELOG.md
src/core/alien/kernels/dok/DoKDistributorComm.cc

Fix bug in parallel redistribution for DoKMatrix

---

CMakeLists.txt
src/core/alien/data/Universe.cc
src/core/tests/CMakeLists.txt
src/core/tests/TestSpacePartition.cc
src/core/tests/TestUniverse.cc
src/movesemantic/tests/CMakeLists.txt
src/refsemantic/tests/CMakeLists.txt

Group unit tests to run faster.
from 45s to 11s on my laptop.

Run unit tests more efficiently

---

CMakePresets.json

Fix #38 
Currently, we provide these configurations:
- minimal
- full
Theses configurations use ninja generator, for better compatibility across OS.

Cmake presets

---

.devcontainer/Dockerfile
.devcontainer/use_spack.sh
CMakePresets.json

Docker development and CMakePresets

IDE config

---

src/movesemantic/alien/move/impl/MatrixMarketReader.cc
src/movesemantic/tests/TestMatrixMarket.cc

Thanks @NathMoller for reporting the issue.

Fix MatrixMarket Vector reader

---

.devcontainer/use_spack.sh
.github/workflows/cmake.yml
.gitignore
plugins/ginkgo/CMakeLists.txt
plugins/ginkgo/bench/CMakeLists.txt
src/CMakeLists.txt
src/core/CMakeLists.txt
src/core/alien/data/CMakeLists.txt
src/core/alien/index_manager/CMakeLists.txt
src/core/alien/kernels/composite/CMakeLists.txt
src/core/alien/kernels/dok/CMakeLists.txt
src/core/alien/kernels/redistributor/CMakeLists.txt
src/core/alien/kernels/simple_csr/CMakeLists.txt
src/core/alien/kernels/sycl/CMakeLists.txt
src/core/alien/utils/CMakeLists.txt
src/movesemantic/alien/move/impl/MatrixMarketReader.cc

- Modernize CMake
- Improve MatrixMarket reader robustness

Code cleanup

---

CHANGELOG.md

Version 1.1.3

---

CMakePresets.json

Spell `RelWithDebInfo` correctly

Fix CMakePresets.json

---

CHANGELOG.md
src/core/alien/index_manager/functional/DefaultAbstractFamily.cc
src/core/alien/index_manager/functional/DefaultAbstractFamily.h
src/core/tests/CMakeLists.txt
src/core/tests/TestFamilies.cc
src/refsemantic/tests/CMakeLists.txt

DefaultAbstractFamily getters were not properly working.
IndexManager code is not properly tested and very complex to understand and to use.
We should:

[core] Fix bug using IndexManager

---

.github/workflows/cmake.yml
CMakeLists.txt
README.md

- Removing SuperLU references
- No default framework, even in dev mode.

Cleaning SuperLU and cmake defaults

---

CMakeLists.txt

Should correct bug observed by @gratienj

[core] fix arccon find package problem

---

.devcontainer/use_spack.sh
.github/workflows/cmake.yml
CMake/fake-framework/FindArccon.cmake
CMakeLists.txt
plugins/ginkgo/CMakeLists.txt
plugins/hypre/CMakeLists.txt
plugins/petsc/CMakeLists.txt
plugins/trilinos/CMakeLists.txt

Use a more standard CMake, Arccon being just a repository of FindPackage files.

Simplify CMake

---

.github/workflows/cmake.yml
.github/workflows/coverity.yml
.github/workflows/docker-publish.yml
.github/workflows/documentation.yml
.github/workflows/format.yml
.github/workflows/ifpen_el7_foss-2018b.yml
.github/workflows/ifpen_el7_gimkl-2018b.yml
.github/workflows/ifpen_el8_foss-2018b.yml
.github/workflows/ifpen_el8_gimkl-2018b.yml

Update actions libraries to their latest releases.

Upgrade CI

---

_clang-format
src/core/alien/core/backend/IInternalLinearAlgebraExprT.h
src/core/alien/core/backend/IInternalLinearAlgebraT.h
src/core/alien/core/backend/LinearAlgebra.h
src/core/alien/core/backend/LinearAlgebraExpr.h
src/core/alien/core/backend/LinearAlgebraExprT.h
src/core/alien/core/backend/LinearAlgebraT.h
src/core/alien/kernels/simple_csr/SimpleCSRMatrix.h
src/core/alien/kernels/simple_csr/algebra/CBLASMPIKernel.h
src/core/alien/kernels/simple_csr/algebra/SimpleCSRInternalLinearAlgebra.cc
src/core/alien/kernels/simple_csr/algebra/SimpleCSRInternalLinearAlgebra.h
src/core/alien/kernels/simple_csr/algebra/alien_cblas.h
src/refsemantic/alien/ref/data/scalar/Matrix.h
src/refsemantic/alien/ref/data/scalar/Vector.h
src/refsemantic/alien/ref/mv_expr/MVExpr.h
src/refsemantic/tests/TestMVExpr.cc

add Matrix expressions

---

src/core/alien/distribution/MatrixDistribution.cc

I am not sure this function is really used.

[core] Bugfix in distribution
